version: 2
jobs:
  build: 
    machine: true
    steps:
      - checkout
      - run: docker build -t openvpn/test:1.2.3 .

  deploy:
    machine: true
    steps:
      - checkout
      - ls -la

    
